version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: budget_backend
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  frontend:
    build:
      context: ./budgeting-app
      dockerfile: Dockerfile
    container_name: budget_frontend
    ports:
      - '5173:5173'
    volumes:
      - ./budgeting-app:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
